### ISSUE TITLE
Add link to MDN browser compatibility report to Insights site.

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/insights#42]
The Google folks helping out with the MDN DNA (Philip Jägenstedt, Robery Nyman, etc.) have created a browser compatibility report to go along with the Web DNA. We'd like to add a link to it to the existing Insights site.

I've made a mockup of what we'd like it to look like:

![Screen Shot 2020-09-12 at 3 40 33 PM](https://user-images.githubusercontent.com/47647/93076372-23cae380-f67f-11ea-8ecb-a9350ff0740d.png)

The only things we need before finalizing this bit of work are:

1. Final sign off from the platform team — i.e. this layout and wording looks OK; Hermina and I have already approved it in principle.
2. The actual report file, so we (Mozilla) can host it and direct the new link to point to it.
3. The size of the report file, so we can replace the current placeholder with the real report size.
4. Agreement on a go-live date for this. I'm assuming this is going to be asap after we get what we need, but I'll get this checked out.

Let me know if you've got any concerns with this; thanks!

**Comment by robnyman** [comment]
Thanks @chrisdavidmills!

2. We're working on it and will get it your way as soon as we can
3. Yep, will share when the PDF is generated
4. From our side, the sooner the better. So agreed on asap, unless it's on a Friday. :-)

@foolip and I will get it done and will let you know.

**Comment by chrisdavidmills** [comment]
@schalkneethling I now have the final PDF for the browser compatibility report from Google; we'll need to host that, in the same way as we do the original Web DNA report. I'll send that over to you.

**Comment by foolip** [comment]
If there's anything special one would have to do, it would be great if the PDF URL is one where the PDF could be updated in place. I expect we'll find a few things we want to update after publication...

**Comment by foolip** [comment]
Looks like the URL will be https://mdn-web-dna.s3-us-west-2.amazonaws.com/MDN-Browser-Compatibility-Report-2020.pdf, although it's still 404.

**Comment by schalkneethling** [comment]
> If there's anything special one would have to do, it would be great if the PDF URL is one where the PDF could be updated in place. I expect we'll find a few things we want to update after publication...

I completely agree that having it separate from the repo is not ideal. I am not sure what the reason was to put it on S3. Perhaps @limed knows?

> Looks like the URL will be https://mdn-web-dna.s3-us-west-2.amazonaws.com/MDN-Browser-Compatibility-Report-2020.pdf, although it's still 404.

Yup, that is expected. It has not been uploaded to S3 yet.

**Comment by limed** [comment]
> > If there's anything special one would have to do, it would be great if the PDF URL is one where the PDF could be updated in place. I expect we'll find a few things we want to update after publication...
> 
> I completely agree that having it separate from the repo is not ideal. I am not sure what the reason was to put it on S3. Perhaps @limed knows?
> 
> If there is no specific reason, perhaps I can add the PDF to the assets folder and link to it relatively from the landing page.
> 
> > Looks like the URL will be https://mdn-web-dna.s3-us-west-2.amazonaws.com/MDN-Browser-Compatibility-Report-2020.pdf, although it's still 404.
> 
> Yup, that is expected. It has not been uploaded to S3 yet.

I went and uploaded it to s3 so it should be there now

**Comment by schalkneethling** [comment]
@chrisdavidmills @limed @robnyman PR merged - https://github.com/mdn/insights/commit/0004ad9192367584ca7bb8662fda142e66ed7587

**Comment by foolip** [comment]
Yay, thanks! I think this issue can be closed now.
