### ISSUE TITLE
Launch Web DNA and 2020 Report

### ISSUE THREAD

**Issue by schalkneethling** [mdn/insights#49]
@chrisdavidmills Plan for launching Web DNA from my side.

- [x] Create a new branch called something like insights-next from master
- [x] Merge my changes into this branch
- [x] Review and probably just merge the PR from Tokyo
- [x] Determine what is needed to build all the bits
- [x] Write this down in a README
- [x] Open PR to `master`
- [x] Ping @limed by EOD(GMT+2) 15 December with details

The goal is that all we need in terms of server architecture is a plain old http server, an S3 bucket, and Cloudfront

**Comment by foolip** [comment]
I was so happy to see the HTML reports launched today, thank you everyone who worked on this!

I noticed an issue in https://insights.developer.mozilla.org/reports/mdn-web-developer-needs-assessment-2020.html that would be great to get fixed quickly, which is that many words have become hypenated, with "orga- nization" being the first example of this in document.

**Comment by foolip** [comment]
I've sent a PR to fix that in https://github.com/mdn/insights/pull/62

**Comment by limed** [comment]
> I've sent a PR to fix that in #62

I just merged this and pushed it to prod, once CI kicks in the new changes should be reflected

**Comment by foolip** [comment]
@limed it looks like https://insights.developer.mozilla.org/reports/mdn-web-developer-needs-assessment-2020.html is not updated yet, did something go wrong with the deploy perhaps?

**Comment by schalkneethling** [comment]
> @limed it looks like https://insights.developer.mozilla.org/reports/mdn-web-developer-needs-assessment-2020.html is not updated yet, did something go wrong with the deploy perhaps?

Looks like this is not been deployed yet @foolip
