### ISSUE TITLE
Questions around in page and inline JS for reports

### ISSUE THREAD

**Issue by schalkneethling** [mdn/insights#67]
Hey All,

I have moved the JavaScript for the GA pieces to an external JavaScript file but, when looking over the 2020 report(for example) I notice there is a big block of JavaScript in the head: https://github.com/mdn/insights/blob/37c59441d92653629b2e4b18efb945793382c349/public/reports/mdn-web-developer-needs-assessment-2020.html#L65

I did some more investigation here and I am not sure how exactly this is all meant to work so, I will need to rely on the folks from Tokyo here. For example, there is a function called `drawChart`, but the call to this function is commented out.

There is also this recursive function: https://github.com/mdn/insights/blob/37c59441d92653629b2e4b18efb945793382c349/public/reports/mdn-web-developer-needs-assessment-2020.html#L97

There is another function called `addCallback` but again, the call to this function is commented out.

There is then another function named `inViewport`. This is used ~115 times. The way this is called seems odd to me. Does this rely on a framework or utility?

https://github.com/mdn/insights/blob/37c59441d92653629b2e4b18efb945793382c349/public/reports/mdn-web-developer-needs-assessment-2020.html#L624

for example:

```
@scroll.window="inViewport($refs.acknowledgements) ? page = '0' : ''"
```

Thoughts @chrisevouk @limed - I guess this is what is tripping us up with regards to the CSP.

**Comment by schalkneethling** [comment]
@chrisevouk Are you using https://developers.google.com/chart/ for mobile specifically? Looking at lines like `google.visualization.arrayToDataTable(data);` I can see the reports definitely use it. Thing is, I don't believe those pages actually import the library?

Although, as mentioned The `drawChart` function is never actually called so, perhaps that is fine.

The `inViewport` function and how it is used, does it perhaps depend on a polyfill for `IntersectionObserver`?

**Comment by chrisevouk** [comment]
No we was for an iteration until Google decided to stick with SVG’s for all.  Now that its all just simple SVGs =that is defunct code/not called so shouldn’t be a problem.

**Comment by schalkneethling** [comment]
I removed the unused JavaScript from the reports here:
https://github.com/mdn/insights/pull/68/files

I guess the question on the table now is, do we:

1. Keep the remaining JS and relax the CSP policy
2. Do we remove the JS and not change the CSP

**Comment by chrisdavidmills** [comment]
Seems to me that we need to try to simplify the code until it works. Remove all the unused JS, do a bit simplification, try to find a balance between "still works ok" and "works on mobile".

I know this comment is going to sound ignorant, and nothing is ever simple with web development, but this is a pretty simple page, and I find it baffling that moving it to production has broken it in such a way.

Even if we just got it to a situation where the menu is removed for now on mobile, so people can actually read the report, that would be better.

Could we push that as a fix for now and then get you folks working together to try to figure out what is going on with this JS?

**Comment by chrisevouk** [comment]
I was just speaking with Sam at our side and he had actually just prepared files I was going to make a PR request for that did exactly the same as this request.

Sam is going to take a look at what’s coming out of the console errors now and suggest some changes to your CSP policy/lambda rules.  This stuff is not my domain, he mentioned it being potential restriction on in-line scripting, though as it all worked fine on our environment we are obviously having to debug after the event.

**Comment by schalkneethling** [comment]
> Sam is going to take a look at what’s coming out of the console errors now and suggest some changes to your CSP policy/lambda rules. 

@limed Can you take a look at these once they are posted? Thank you.

**Comment by samuelbirch** [comment]
Hey Guys,

These are the issues that at being raised in the browser console.

```
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' *.google-analytics.com 'sha256-tSAfTBDI9GnqRGwSZkJvYTf662VRLJNAXe5ccqzpauw='". Either the 'unsafe-inline' keyword, a hash ('sha256-mvsAMOT/4lZBh+6zEhsa3CZ2VL0e1QDkjlne9LmO+P8='), or a nonce ('nonce-...') is required to enable inline execution.

Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' 'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='". Either the 'unsafe-inline' keyword, a hash ('sha256-0EZqoz+oBhx7gF4nvY2bSqoGyy4zLjNF+SDQXGp/ZrY='), or a nonce ('nonce-...') is required to enable inline execution.

Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' *.google-analytics.com 'sha256-tSAfTBDI9GnqRGwSZkJvYTf662VRLJNAXe5ccqzpauw='".
```

Are you able to add the hashes to your CSP?

**Comment by schalkneethling** [comment]
> These are the issues that at being raised in the browser console.

@samuelbirch What functionality do we lose if we remove the `inViewport` and related code? My concern is that, even if we allow inline JS execution, this will still fail:

```
@scroll.window=
```

**Comment by chrisdavidmills** [comment]
This won't happen until our devops guy wakes up over on the west coast. For now, can we apply a bandaid that will at least make it somewhat usable on mobile, for example just hiding the menu on narrow viewports?

**Comment by samuelbirch** [comment]
> > These are the issues that at being raised in the browser console.
> 
> @samuelbirch What functionality do we lose if we remove the `inViewport` and related code? My concern is that, even if we allow inline JS execution, this will still fail:
> 
> ```
> @scroll.window=
> ```

this bit of code opens and highlights the navigation as you scroll down the page.

**Comment by schalkneethling** [comment]
@samuelbirch Ok, so I guess the polyfill is bundled in `<script src="assets/js/main.094bca66.js"></script>`

**Comment by samuelbirch** [comment]
@schalkneethling the only thing bundled in `main.094bca66.js` is alpine.js

**Comment by chrisevouk** [comment]
So @samuelbirch is there a bandaid solution that could just get mobile working for now?

**Comment by samuelbirch** [comment]
@chrisevouk i'll create a PR that hides the nav on narrow viewports

**Comment by schalkneethling** [comment]
> @schalkneethling the only thing bundled in `main.094bca66.js` is alpine.js

Ah, and I guess it adds support for things like `@scroll` and `@click` etc.

**Comment by schalkneethling** [comment]
> @chrisevouk i'll create a PR that hides the nav on narrow viewports

I was just about to do the same thing :)

**Comment by schalkneethling** [comment]
@samuelbirch There has been some merged to master so, just make sure you pull before creating the feature branch and opening a PR. Thank you!

**Comment by samuelbirch** [comment]
i've created the PR: https://github.com/mdn/insights/pull/69

**Comment by schalkneethling** [comment]
> i've created the PR: #69

merged.
