### ISSUE TITLE
Missing links in MDN Browser Compatibility Report 2020

### ISSUE THREAD

**Issue by foolip** [mdn/insights#70]
I noticed only now that many links are missing in https://insights.developer.mozilla.org/reports/mdn-browser-compatibility-report-2020.html compared to our original PDF. This is most apparent when looking at the "See also" lists, which aren't very useful at all without the links.

@robnyman FYI

**Comment by chrisevouk** [comment]
This is being picked up by @samuelbirch this weekend.

We have created a document highlighting the links that need rectifying and we have forked mdn/insights.
Once the HTML has been updated to include the missing hyperlinks we will create PR.

**Comment by chrisevouk** [comment]
Note just serving as a remember to tag @chrisdavidmills in PR per request of Robert by email.

**Comment by schalkneethling** [comment]
@foolip Can we close this one?

**Comment by foolip** [comment]
@schalkneethling yes, this was fixed! :)
