### ISSUE TITLE
Zilla font not loading on HTML reports

### ISSUE THREAD

**Issue by schalkneethling** [mdn/insights#90]
The Zilla font family fails to load on insights, perhaps missing assets?

**Comment by Zaidtech** [comment]
@schalkneethling  Can i work on this issue?

**Comment by schalkneethling** [comment]
> @schalkneethling Can i work on this issue?

I am not sure whether this is still an issue to be honest. If you find that it still is, you are more than welcome to contribute. Thank you!

**Comment by Zaidtech** [comment]
@schalkneethling  let me have a look.
